### ISSUE TITLE
User Info page

### ISSUE THREAD

**Issue by scripting** [scripting/a8c-FeedLand-Support#56]
We have Feed Info and Reading List info but until now, no User Info page.

This missing piece made it hard to sort out problems in Supervisor mode. 

Seemed like a one-day project, and it is shaping up that way.

**Comment by cagrimmett** [comment]
Small bug with the first version of the user info page: Links to feed list and latest news go to the current logged in user's feed list and latest news rather than the feed list and latest news for the user whose info page you are viewing.

Steps to reproduce:
1. Go to anyone's user info page but your own. For example, https://feedland.org/?userinfo=bullmancuso
2. Under the `View as` section, click either the Feed list or Latest News link. 
3. You'll be taken to your own feed list or latest news, when you'd expect to go to https://feedland.org/?username=bullmancuso or https://feedland.org/?river=true&screenname=bullmancuso


![Image](https://github.com/scripting/a8c-FeedLand-Support/assets/8738771/6bd28e71-53e5-47d6-8f64-30e9b7b8b7c7)

**Comment by scripting** [comment]
@cagrimmett -- thanks for the report. fixed. ;-)

**Comment by scripting** [comment]
New feature -- the category names are linked to the Feed List page for the user whose info we're looking at.



![Image](https://github.com/scripting/a8c-FeedLand-Support/assets/1686843/a9a99b60-902e-4ff7-b10d-32faefcf729d)
