### ISSUE TITLE
Duplicate subscriptions

### ISSUE THREAD

**Issue by cagrimmett** [scripting/a8c-FeedLand-Support#77]
The past week I've noted a number of duplicate subscriptions in my feed list. Examples:

- I'm subscribed twice: https://feedland.com/?feedurl=https%3A%2F%2Fstephanango.com%2Ffeed.xml
- I'm subscribed three times: https://feedland.com/?feedurl=https%3A%2F%2Frobinrendle.com%2Ffeed.xml
- I'm subscribed three times: https://feedland.com/?feedurl=https%3A%2F%2Fdaverupert.com%2Fatom.xml
- davewiner is subscribed twice: https://feedland.com/?feedurl=https%3A%2F%2Fma.tt%2Ffeed

As such, these feeds show up multiple times in my feed list. I need to watch for one of them to post to see if the posts shows multiple times in my River.

It looks like this has something to do with Reading Lists. I don't think it is a _bug_ per se, just an unintended consequence. Still, seeing the same feed listed multiple times, or seeing your own username listed multiple times on the subscription page, feel wrong. We should have some kind of duplicate checking on subscribing and in list views.

**Comment by scripting** [comment]
@cagrimmett -- thanks for this report. ;-)

They are distinct subscriptions, by design. The ones that are from a reading list should appear in green type, and if you hover over the info icon (rightmost column) it should say so in the popup window.

I don't think you'll see multiple versions of the same post in timelines because there is a specific protection against showing an item more than once, there are other ways it can happen. 

I don't think there's any need to show the user's name multiple times in the subscriber list in the feed info page for the feed.

**Comment by scripting** [comment]
@cagrimmett -- i believe i have fixed this, so that a name appears no more than once in the subscribers list.

i've tested with each of the examples you provided. (a very good practice in reporting bugs, btw)

**Comment by cagrimmett** [comment]
Thank you, @scripting !
